### ISSUE TITLE
Certain URIs not handled properly

### ISSUE THREAD

**Issue by davidfischer** [davidfischer/requirements-parser#16]
I'll fix these, but I figure I should at least document what doesn't work. Basically these aren't quite URIs.

    bzr+lp:MyProject#egg=MyProject
    git+git@git.myproject.org:MyProject#egg=MyProject

Because they aren't URIs, they are assumed to be "local files" which isn't correct.

**Comment by mshenfield** [comment]
Looks like this has been fixed with the addition of VCS schemes.

**Comment by davidfischer** [comment]
Yay! https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
