### ISSUE TITLE
Question: New release including recursive parsing?

### ISSUE THREAD

**Issue by tobiasweibel** [davidfischer/requirements-parser#20]
Hi David

Would it be possible to release a new version including [recursive parsing commit](https://github.com/davidfischer/requirements-parser/commit/fa55463ddc3e08c652308c29dbd31dceb41564c8)?

Best regards
Tobias

**Comment by jessamynsmith** [comment]
I would also like this very much!

**Comment by davidfischer** [comment]
I'll make a release today. I always welcome PRs.

**Comment by davidfischer** [comment]
There is a new release for recursive parsing and a fix for packages with underscores:
https://pypi.python.org/pypi/requirements-parser/0.1.0

Cheers!

**Comment by tobiasweibel** [comment]
Thanks!
