### ISSUE TITLE
Support hash fragment in uri matcher (e.g `#md5=...`)

### ISSUE THREAD

**Issue by mshenfield** [davidfischer/requirements-parser#22]
The [URI regular expression](https://github.com/davidfischer/requirements-parser/blob/c84b72ad3f4318832cf87f9610c2f7a49c590964/requirements/requirement.py#L8) doesn't support hashes in the fragment portion. Because of this, these urls are ignored, and passed to pkg_resources parse, which fails in a confusing way.

``` python
import requirements
list(requirements.parse("http://pypi.python.org/packages/source/p/pytz/pytz-2012b.tar.gz#md5=6c47456aca37bec88b3c6f4b02db613a"))
# > RequirementParseError: Invalid requirement, parse error at "'://pypi.'"
```

Adding support for a hash fragment would be great!

**Comment by davidfischer** [comment]
These no longer fail after merging #23. However, I suppose it would be nice to try to get any additional information from the URL.

**Comment by davidfischer** [comment]
Thanks for fixing this in #24!
