### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by sbidoul** [davidfischer/requirements-parser#36]
@davidfischer do you plan a new release to pypi? 

It would be great to have the last improvements in the released version.

I'd be happy to help making this happen if needed.

**Comment by davidfischer** [comment]
Sure thing. I can try to make a release in the next day or two.

**Comment by davidfischer** [comment]
https://pypi.python.org/pypi/requirements-parser/0.2.0

Let me know if you encounter any issues. It's been a while since I made a release and bugs are possible!

**Comment by sbidoul** [comment]
Thanks a bunch!

Nice to have: since it works on py 2 and 3, you could create a [universal wheel](https://packaging.python.org/tutorials/distributing-packages/#universal-wheels).
